#!/bin/sh

FOCUSED_FG=$BRIGHT_WHITE
FOCUSED_BG=$BRIGHT_BLACK

ACTIVE_FG=$WHITE
ACTIVE_BG=$BLACK

NORMAL_FG=$WHITE
NORMAL_BG=$BLACK

URGENT_FG=$BRIGHT_WHITE
URGENT_BG=$BRIGHT_RED


PRIMARY_SCREEN_RHS=
SCREEN_RHS=

CLOCK_OUTPUT=
UPOWER_OUTPUT=

while read LINE; do
    case "$LINE" in
        c*)
            CAFFEINE_OUTPUT="${LINE#?}"
            ;;
        C*)
            CLOCK_OUTPUT="${LINE#?}"
            ;;
        P*)
            UPOWER_OUTPUT="${LINE#?}"
            ;;
        #W*)
        #    DESKTOP_OUTPUT=
        #    IFS=':'
        #    set -- ${LINE#?}
        #    while [ $# -gt 0 ]; do
        #        ITEM=$1
        #        name=${ITEM#?}
        #        case $ITEM in
        #            [mM]* )
        #                case $ITEM in
        #                    m* )
        #                        ;;
        #                    M* )
        #                        ;;
        #                    * )
        #                        ;;
        #                esac
        #                ;;
        #            [fFoOuU]* )
        #                case $ITEM in
        #                    [fF]* )
        #                        FG=$NORMAL_FG
        #                        BG=$NORMAL_BG
        #                        ;;
        #                    [oO]* )
        #                        FG=$FOCUSED_FG
        #                        BG=$FOCUSED_BG
        #                        ;;
        #                    [uU]* )
        #                        FG=$URGENT_FG
        #                        BG=$URGENT_BG
        #                        ;;
        #                esac
        #                ;;
        #            * )
        #                ;;
        #        esac
        #    done
        #    ;;
        *)
            ;;
    esac

    PRIMARY_MONITOR_NAME="$(xrandr | awk '/ primary /{print $1}')";
    PRIMARY_MONITOR_INDEX=
    
    MONITOR_RHS="$CLOCK_OUTPUT";
    PRIMARY_MONITOR_RHS="$CAFFEINE_OUTPUT$UPOWER_OUTPUT$MONITOR_RHS";

    case "$LINE" in
        W* )
            DESKTOP_OUTPUT=;
            NUMBER_OF_MONITORS=0;
			IFS=':';
			set -- "${LINE#?}";
			while [ "$#" -gt 0 ] ; do
				item=$1
				name=${item#?}
				case "$item" in
					[mM]*)
						case "$item" in
							m*)
								# monitor
								;;
							M*)
								# focused monitor
								;;
                        esac
                        $NAME=$name;
                        if [ "$PRIMARY_MONITOR_NAME" = "$name" ]; then
                            PRIMARY_MONITOR_INDEX="$NUMBER_OF_MONITORS";
                        fi
                        NUMBER_OF_MONITORS="$(expr $NUMBER_OF_MONITORS + 1)";
						;;
					[fFoOuU]*)
						case "$item" in
							f*)
								# free desktop
								;;
							F*)
                                # focused free desktop
								;;
							o*)
								# occupied desktop
								;;
							O*)
                                # focused occupied desktop
								;;
							u*)
								# urgent desktop
								;;
							U*)
                                # focused urgent desktop
								;;
						esac
						;;
					[LTG]*)
						# layout, state and flags
						;;
				esac
				shift
			done

            ;;
        * )
            ;;
    esac
    
    OUTPUT=
    i=0
    MONITORS="$(xrandr -q | awk -e '/[a-zA-Z0-9] connected/{print $1}')";
    for MONITOR in $MONITORS ; do

        if [ "$PRIMARY_MONITOR_INDEX" -eq "$i" ]; then
            OUTPUT="$OUTPUT%{S$i}%{c}primary%{r}$PRIMARY_MONITOR_RHS";
        else
            OUTPUT="$OUTPUT%{S$i}%{c}$NAME%{r}$MONITOR_RHS";
        fi
        i="$(expr $i + 1)";
    done

    echo "$OUTPUT";
done
