#!/bin/env lua

local io = io

io.stdin:setvbuf('line')
io.stdout:setvbuf('line')

local lines = io.stdin:lines()

local monitor = {
    new = function (self, obj)
        obj = obj or {}
        self.__index= self
        return setmetatable (obj, self)
    end,
    
}

function monitor.new(self, obj)
    obj = obj or {}
    self.__index= self
    return setmetatable (obj, self)
end


local function create_monitors(nodes)
    local monitors = {}
    local monitor
    for i,node in ipairs(nodes) do
        if node:match('[W]?[Mm]+') then
            table.insert(monitors, monitor)
            monitor = {
                position = i,
                name = node:match('W]?[Mm]([a-zA-Z0-9]+)')
            }
        end
        table.insert(monitor, node)
    end
    for i,monitor in ipairs(monitors) do
        
    end
end

local function handle_line(line)
    local nodes = {}
    for node in line:gmatch('[^:]+') do
        table.insert(nodes, node)
    end
    local monitors = create_monitors(nodes)

end

for line in lines do
    if line then 
        handle_line(line)
    end
end
