#!/bin/lua
local io = io
local math = math

local lemonaid = require('lemonaid')

local lgi = require('lgi')

local GLib = lgi.GLib
local UPowerGlib = lgi.UPowerGlib
local Device = UPowerGlib.Device


local fifo = io.open(args[1], 'a')
fifo:setvbuff('line')

local render_on_kind = {
    battery = function (device)
        
    end,
    [line-power] = function (device)
        
    end,
    mouse = function (device)
        
    end
}


local upower = {
    devices = {},
    devices_lookup = {},
    render_widget = function (self)
        local line = ''
        if self.display_device.kind == 0 then
            for _,device in ipairs(self.devices) do
                line = line .. render_on_kind(device)
            end
        else
            line = render_on_kind(self.display_device)
        end
        fifo.write(line..'\n')
    end
}

upower.client = UPowerGlib.Client {
    
}

upower.display_device = upower.client:get_display_device {

}



local mainloop = GLib.MainLoop(nil, false)
mainloop:run()
