#!/bin/sh
KEYBOARD_BACKLIGHT_TRIGGER=20
KEYBOARD_BACKLIGHT_LOW=0
KEYBOARD_BACKLIGHT_HIGH=50

SCREEN_BACKLIGHT_INCREMENT=5
SCREEN_BACKLIGHT_INCREMENT_SETTINGS="" #-fps 60 -time 100"

acpi_listen | while read -r button event data; do
    case $event in
        BRTUP|BRTDN)
            currentScreenBackight=`xbacklight -ctrl intel_backlight -get`
            case $event in
                BRTUP)
                    if [ $currentScreenBackight -eq 1 ]; then
                        xbacklight -ctrl intel_backlight -set $SCREEN_BACKLIGHT_INCREMENT $SCREEN_BACKLIGHT_INCREMENT_SETTINGS
                    else
                        xbacklight -ctrl intel_backlight -inc $SCREEN_BACKLIGHT_INCREMENT $SCREEN_BACKLIGHT_INCREMENT_SETTINGS
                    fi
                    ;;
                BRTDN)
                    if [ $currentScreenBackight -gt $SCREEN_BACKLIGHT_INCREMENT ]; then
                        xbacklight -ctrl intel_backlight -dec $SCREEN_BACKLIGHT_INCREMENT $SCREEN_BACKLIGHT_INCREMENT_SETTINGS
                    else
                        xbacklight -ctrl intel_backlight -set 1 $SCREEN_BACKLIGHT_INCREMENT_SETTINGS
                    fi
                    ;;
            esac
            currentScreenBackight=`xbacklight -ctrl intel_backlight -get`
            if [ $currentScreenBackight -le $KEYBOARD_BACKLIGHT_TRIGGER ]; then
                xbacklight -ctrl tpacpi::kbd_backlight -set $KEYBOARD_BACKLIGHT_HIGH
            else
                xbacklight -ctrl tpacpi::kbd_backlight -set $KEYBOARD_BACKLIGHT_LOW
            fi
            ;;
        LID)
            case $data in
                open)
                    ;;
                close)
                    xlock -mode blank
                    ;;
            esac
            ;;
    esac
done
