#!/bin/sh

CURRENT_MONITOR="$(bspc query -M focused -m)"

CURRENT_DESKTOP="$(bspc query -D focused -d)"

STACK_FILE="${XDG_RUNTIME_DIR:-/tmp}/$CURRENT_MONITOR.$CURRENT_DESKTOP.hide.stack";

WINDOW_ID="$(bspc query -N focused -n)";

if [ ! -z "$WINDOW_ID" ]; then
    stack push "$WINDOW_ID" "$STACK_FILE";
    bspc node "$WINDOW_ID" --flag hidden;
fi

