#!/bin/sh

PANEL_FIFO="$XDG_RUNTIME_DIR/panel.fifo"
[ ! -e "$PANEL_FIFO" ] && mkfifo "$PANEL_FIFO"

FONT="-*-terminus-*-*-*-*-*-*-*-*-*-*-*-*"

start_bar() {
    tail -f "$PANEL_FIFO" | $HOME/.config/panel/panelrc | lemonbar -f  "$FONT" -F "$FOREGROUND"  -B "$BACKGROUND" -g "x$PANEL_HEIGHT"
}


start_service() {
    [ -x $HOME/.config/panel/widgets/$1 ] && $HOME/.config/panel/widgets/$1 $PANEL_FIFO
}

#$@

COMMAND=$1

shift

case $COMMAND in
    start )
        start_$@
        ;;
    stop )
        ;;
    restart )
        ;;
    * )
        usage
        ;;
esac
