#! /bin/sh

## get colors

get_color() {
    xrdb -query | grep "*.color$1:" | cut -f 2
}

BACKGROUND="$(xrdb -query | grep "*.background:" | cut -f 2)"
FOREGROUND="$(xrdb -query | grep "*.foreground:" | cut -f 2)"

BLACK="$(get_color 0)";
BRIGHT_BLACK="$(get_color 8)";

RED="$(get_color 1)";
BRIGHT_RED="$(get_color 9)";

GREEN="$(get_color 2)";
BRIGHT_GREEN="$(get_color 10)";

YELLOW="$(get_color 3)";
BRIGHT_YELLOW="$(get_color 11)";

BLUE="$(get_color 4)";
BRIGHT_BLUE="$(get_color 12)";

MAGENTA="$(get_color 5)";
BRIGHT_MAGENTA="$(get_color 13)";

CYAN="$(get_color 6)";
BRIGHT_CYAN="$(get_color 14)";

WHITE="$(get_color 7)";
BRIGHT_WHITE="$(get_color 15)";

export BACKGROUND FOREGROUND
export BLACK RED GREEN YELLOW BLUE MAGENTA CYAN WHITE
export BRIGHT_BLACK BRIGHT_RED BRIGHT_GREEN BRIGHT_YELLOW BRIGHT_BLUE BRIGHT_MAGENTA BRIGHT_CYAN BRIGHT_WHITE
export PADDING=6

export PANEL_HEIGHT=16;

## one offs
xsetroot -cursor_name left_ptr &
feh --bg-scale "$HOME/.config/bspwm/wallpaper.png" &

## bspwm

# get monitors
MONITORS="$(xrandr -q | awk -e '/[a-zA-Z0-9] connected/{print $1}')";
for MONITOR in $MONITORS ; do
    bspc monitor "$MONITOR" -d 1 2 3 4 5 6 7 8 9 &
done

# borders and gaps
bspc config normal_border_color "$BLACK"
bspc config active_border_color "$BRIGHT_BLACK"
bspc config focused_border_color "$WHITE"
bspc config presel_feedback_color "$BLACK"

bspc config border_width 1
bspc config window_gap 8
bspc config top_padding "$PANEL_HEIGHT"
bspc config bottom_padding "$PANEL_HEIGHT"

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config presel_feedback true

# mouse config
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bpsc config pointer_follows_monitor true

# rules
bspc rule -a discord desktop='^9' focus=off
bspc rule -a Steam desktop='^8' focus=off
bscp rule -a mpv desktop='^7' focus=off

## panel

list_descendants ()
{
  local children=$(ps -o pid= --ppid "$1")

  for pid in $children
  do
    list_descendants "$pid"
  done

  echo "$children"
}


pgrep -f 'panel start bar' || panel start bar &
pgrep -f 'panel start service clock' || panel start service clock &
pgrep -f 'panel start service caffeine' || panel start service caffeine &


optional_service() {
    which "$1" >> /dev/null && $@
}

## services
pgrep -x xcompmgr || xcompmgr -ncf -D 5 &
pgrep -x xbanish || xbanish &
pgrep -x sxhkd || sxhkd -t 1 &
pgrep -x start-pulseaudio-x11 || start-pulseaudio-x11 &
pgrep -x mpd || mpd &
pgrep -x mpDris2 || mpDris2 &
pgrep -x xss-lock || xss-lock lock &
pgrep -x Discord || Discord &
pgrep -x steam || optional_service steam &
pgrep -x ckb-next || optional_service ckb-next -b &

